// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4KtEl2eXmVyXeRo7hdOYocSOEk0Fvx5A',
    appId: '1:201487746696:web:ada81ccb85a838a19fc13d',
    messagingSenderId: '201487746696',
    projectId: 'jspims',
    authDomain: 'jspims.firebaseapp.com',
    storageBucket: 'jspims.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGul1eZLMQEuQpmmjxcNMnIt5zX5UlDzs',
    appId: '1:201487746696:android:35bb56ef68a4c92b9fc13d',
    messagingSenderId: '201487746696',
    projectId: 'jspims',
    storageBucket: 'jspims.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfum5aqs7ptJRyaNTwhQK9hcK9EwU9BY0',
    appId: '1:201487746696:ios:a47a926e38848e1d9fc13d',
    messagingSenderId: '201487746696',
    projectId: 'jspims',
    storageBucket: 'jspims.firebasestorage.app',
    iosBundleId: 'com.example.juhaynaSmartProductionAndInventoryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfum5aqs7ptJRyaNTwhQK9hcK9EwU9BY0',
    appId: '1:201487746696:ios:a47a926e38848e1d9fc13d',
    messagingSenderId: '201487746696',
    projectId: 'jspims',
    storageBucket: 'jspims.firebasestorage.app',
    iosBundleId: 'com.example.juhaynaSmartProductionAndInventoryManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4KtEl2eXmVyXeRo7hdOYocSOEk0Fvx5A',
    appId: '1:201487746696:web:4207ae13a780f9c79fc13d',
    messagingSenderId: '201487746696',
    projectId: 'jspims',
    authDomain: 'jspims.firebaseapp.com',
    storageBucket: 'jspims.firebasestorage.app',
  );
}
